### ISSUE TITLE
Membership & Email Signup Flow Strawman

### ISSUE THREAD

**Issue by mikeal** [nodejs/board#10]
Goals:
1. Maintain a single point of administration for lists of members and teams under the foundation.
2. Leverage GitHub repositories for the communication and archive capacity whenever possible.
3. Automate as much of the process as possible.

Signup Flow
1. A potential member logs in to GitHub through a web form at membership.nodejs.org
2. If they are a member of the `nodejs` GitHub org they are offered free membership, otherwise they are asked to pay a fee ($25 student, $99 individual).
3. They succeed in signing up as a member.
4. They are added/invited to the `node-foundation` GitHub org and added to the `members` team.

A cron job runs every hour which syncs the state of members in the `node-foundation` GitHub org with our email system (using mailgun).

Sync Service
1. Pulls every user in the `members` team and forward <github-username>@nodejs.org to the email address in their GitHub profile.
2. Pulls the members of the `security` teams and routes security@nodejs.org to that team.

I'm not sure yet if there is a good reason to have any other email forwards. We can use GitHub private repos for any sensitive information and we have the benefit of an archive for new members coming in to those groups -- not to mention we have the use of public repos for _most_ communication.

If we need to do an email campaign to all member that should be as simple as pulling the list of all members and sending them an email through mailchimp.

**Comment by guyellis** [comment]
Comments:

`2`. Optionally able to donate more than membership fee when signing up.

`4`. How do notifications for renewal happen? How does expiration removal happen? (I'm guessing that you're ignoring this for now because there's a year+ before this needs to be addressed.)

Just to clarify, every member _must_ have a GitHub account. (I can't think of anyone who would not.)

**Comment by bnb** [comment]
@guyellis Comments on comments:

`2.` I would like to donate as well, despite being a member of the `nodejs` org. Crossing over to an issue I was just writing to (https://github.com/nodejs/evangelism/issues/91), a donate feature would be good to have in general - some people might want to donate and not become a member. This would also set us up for things like 24 hour fundraiser livestreams for funding the foundation and charity events.

**Comment by Morgul** [comment]
> `4.` They are added/invited to the node-foundation GitHub org and added to the members team.

Just want to highlight the potential problem with this and `2.` when renewing. The check needs to be 'are they a member of the org _outside_ of the members team?'. Otherwise the renewal will always be free. :)

Over all, I like what's outlined. I do agree with @guyellis and @bnb that we will want some way to do additional donations, beyond the minimum, but that could be solved through a dedicated donation button, and a link from the membership form to said button. (aka: "Want to donate more than the membership fees? Go here to donate.")

**Comment by mikeal** [comment]
> Just want to highlight the potential problem with this and 2. when renewing. The check needs to be 'are they a member of the org outside of the members team?'. Otherwise the renewal will always be free. :)

This is why we have a `node-foundation` org that is separate from the `nodejs` org :)

> donations and renewals

If we use Stripe there is a way to add a recurring charge per year but that might make it difficult to also add donations on top of the regular payment.
