### ISSUE TITLE
Q&A w/ @guyellis on Individual Membership Candidacy

### ISSUE THREAD

**Issue by mikeal** [nodejs/board#19]
This thread is for asking @guyellis questions regarding [his run](http://www.guyellisrocks.com/2015/11/node-foundation-membership-election.html) for the Node.js Foundation Board of Directors.

**Comment by rosskukulinski** [comment]
Hi @guyellis!  First of all, thank you for running for the Node Board.  I read your post and I was hoping you could expand more on this statement:

> I would like to be able to help shape the success of this platform. One way to do that is to understand what the membership wants and needs to get out of what we have today. More importantly what do they expect from the future. 

In particular, I'm wondering how you plan to reach out to the existing (and new/growing) user base to understand our needs.

I also am curious about your personal stance on the node ecosystem.  Representing the community is an important aspect of this position, but as you've worked with node a while I would expect you have your own passions, views, and ideas.  What do _you_ want to see happen with Node in the next 3-24 months?

Side note: I love your [project-health](https://github.com/guyellis/project-health) repo

**Comment by jasnell** [comment]
(A) If elected, what do you envision would be three most important issues that need to be addressed and how would you go about advocating for / resolving those?

(B) In a single sentence, how would you describe the role of the person elected to the board?

**Comment by junosuarez** [comment]
1. What do you see as the most significant obstacle to node.js's continued growth?
2. What do you think the node.js foundation can do to address your answer to #1?

**Comment by guyellis** [comment]
Those are great questions - thank you for asking.

@rosskukulinski

> reaching out to existing/new user base

Interacting with (potential) Node developers through day-to-day work, on social media, at meet-ups and at conferences. More in response to @jasnell below.

> What do _you_ want to see happen with Node in the next 3-24 months?

I want to see Node continue along its current trajectory without fragmentation. I think that the most difficult hurdle that Node has had to face in its short history was the reunification of io.js back into Node and the formation of a foundation that was acceptable to all parties. A great testament to the maturity and dedication of all people and parties involved.

I believe that that stability is key to growth. Expanded in answer to @jden below.

@jasnell

> (A) three most important issues that need to be addressed and how would you go about advocating for / resolving those
- Tooling
  - When you compare the developer experience of a Visual Studio developer to that of a Node developer they are vastly different. The majority of existing Node developers are not interested in the Visual Studio experience, they are happy with most of the tooling they currently have. For developers who are new-to-Node and/or new-to-software-development, coming into Node can be jarring compared to using something like Visual Studio. I would like more people to answer the question “As a beginner what language/platform do you suggest I learn?” with “JavaScript/Node.”
  - Advocating for/resolving this:  Find and support projects which “ease” developers into the Node development environment with the right tools.
- Zero to Hero
  - This is somewhat related to the first point on Tooling. In order to get up-and-running with the right environment/configuration/modules can take a certain effort and have some challenges.
  - Advocating for/resolving this: I feel that we need to have one or more community run Recipes and Getting Started resources. Starting with what are the most common problems/application that Node provides a solution to and what are the popular approaches to getting there. Once the common cases have been documented we move onto less the common…
- Perception
  - A developer once said to me: “You wouldn’t use Node for that. Ruby is for building websites and APIs, Node is for real-time chat applications.” As members of the Node community and understanding and knowing what it’s good for and capable of doing it’s easy to not notice the perception that others outside the community have of the product.
  - Advocating for/resolving this: Objective evangelism. We need to understanding that other developers’ platforms and languages are an important part of their identities. When advocating Node as a possible solution to (part of) their problems we need to be sensitive to their areas of expertise and existing investment. Be active in the development community and not just the Node community provides an avenue to resolving this if approach with tact and diplomacy.

> (B) ...how would you describe the role of the person elected to the board?

To act as one of many conduits between the developer community and the board to raise concerns, provide feedback and complete tasks that will further the stability and progress of Node and its community.

@jden

> 1. What do you see as the most significant obstacle to node.js's continued growth?

I feel that the splinter into io.js was a necessary and beneficial step to where we are today. I can see that a fracture in the Node community may dilute the reunified effort that we now have and that would have a negative impact on continued growth.

> 1. What do you think the node.js foundation can do to address your answer to this?

Because of the history of the io.js fork and what the community learned from it I think that everyone serving on the Node Foundation board are acutely aware of this. It’s important that we pay attention to what’s happening. Discord in the community is unlikely to happen overnight. It’s more likely to be a gradual process built on a number of events. We will need to be able to discuss these issues openly to ensure that dissolution in the community is kept to a minimum.

One of @mikeal presentations showed how contributions significantly increased in the io.js codebase after it was forked. This provided confirmation from the community that this was the way that most of the community wanted to go. It’s great to be able to measure and confirm something like that. It would be even better if that could have been measured and acted on by the community without the fork happening. Preventing instead of remediating will be better for Node and the community.

**Comment by rvagg** [comment]
Thanks for the great responses in here @guyellis, and thanks for nominating!

**Comment by mikeal** [comment]
Election is over, results are [posted](https://github.com/nodejs/membership/blob/master/README.md#2016-election).
