### ISSUE TITLE
Q&A w/ @sup on Individual Membership Candidacy

### ISSUE THREAD

**Issue by mikeal** [nodejs/board#20]
This thread is for asking @sup questions regarding [his run](http://jona.io/blog/board-application/) 
for the Node.js Foundation Board of Directors.

**Comment by jasnell** [comment]
(A) If elected, what do you envision would be three most important issues that need to be addressed and how would you go about advocating for / resolving those?

(B) In a single sentence, how would you describe the role of the person elected to the board?

**Comment by ghost** [comment]
@jasnell 
(A) one of the most important ones is definitely increasing inclusivity and diversity within the contributor base, but also in general focusing on making it easier to get into contributing. the current state is that the most 'important' repos like node or website have a lot of active contributors, but it's especially lacking around the newer WGs like docs. in order to increase inclusivity, the inclusivity WG has been formed, thus now it is important to embrace their work and ideas. 

while those issues might not be that apparent, i believe that they're very important in order to keep the internal structure of the project itself.

the third issue would be moderation. we've seen quite the uproar over an issue in the node core recently, which has brought up said issue. what's important now is to clarify a process for dealing with these sort of exceptions, and to see what we can learn from them.

as though these issues are at an early stage of being dealt with, i'm certain that once we've overcome them, the whole project will profit from it.

(B) "a board member representing the whole of the contributor base, who therefore is expected to convey the peoples' opinions accurately"

**Comment by rosskukulinski** [comment]
Hello @sup - thank you for applying to the Board!  I read your application and I completely agree your (or anyone's) age shouldn't matter.  Following up on your response (B) to @jasnell, how do you plan on listening to (and then conveying) the large (and growing) Node ecosystem?

**Comment by ghost** [comment]
@rosskukulinski hello ross! what you asked is a very good question - as such there's multiple ways to go about it. what i'd personally endorse is to monitor social media more closely for node itself. that includes trends on github, which are known to rapidly change, and are therefore a good indicator on global trends in the open source world. perhaps we can put the evangelism WG in charge of this, since as far as i know, they're already operating the social media accounts.

but then again, that's only one facet of the issue. let me know if i should touch on another subject or further explain my 'theories'!

**Comment by junosuarez** [comment]
1. What do you see as the most significant obstacle to node.js's continued growth?
2. What do you think the node.js foundation can do to address your answer to #1?

**Comment by ghost** [comment]
@jden 
1. right now the project is experiencing some major issues within its contributor base, which relates to the issues i've covered in my answer to @jasnell. i believe that this is the most important thing to resolve, otherwise bad things will happen, and eventually there'll be a community fork again.
2. could you clarify what you mean by #1? i'm not sure what you're referring to by that

**Comment by defnorep** [comment]
Hello @sup,

Can you please clarify a part of your answer to @jden?

You replied:

> "i believe that this is the most important thing to resolve, otherwise bad things will happen, and eventually there'll be a community fork again."

I'm uncertain what you mean by "bad things will happen". Could you share some of your insight?

**Comment by ghost** [comment]
@daekano of course. what i mean is that there is likely to be dissatisfaction with the contributor base, which, in turn, will cause a chain reaction that will end up in either people leaving the project or making a new fork. this can be observed with io.js, where the initiators were unhappy with the state and governance of the project. the same thing is also happening with meteor, which is (also) governed by a core development group.

**Comment by defnorep** [comment]
I worry I might be departing from the Q&A format here; if this style of dialogue is not intended please just let me know.

@sup: I believe that the fork of Node and the eventual convergence of IO and Node was a good thing, not a bad thing. I would like to ensure that the community has the tools to make or act upon their decisions, forking being a compatible tool for open source software. There is always some measure of discussion or argument in any decision making process, and I'm not so sure that striving for the easiest and most friction-free solution will always be in the best interest of the community, nor the product. Open source software depends on everyone's viewpoint at all times, free of censorship on all sides. That is when diversity shines.

Anyways, thank you for your time, and I wish you the best with your endeavours with the foundation :)

**Comment by junosuarez** [comment]
@sup 

> i'm not sure what you're referring to by that

Sorry, I meant my first question, not github's autolinked issue number 1 :)

So, you said resolving issues with the contributor base is the largest obstacle to node.js's growth- how do you feel the foundation can address them?

**Comment by ghost** [comment]
@jden there's multiple good ways to go about it. i believe that the first step could be to gather information about the general state within the collaborator base, perhaps through a survey or another medium.

after we have a concrete description of the most important issues, we need to start resolving them. one idea might be to create a moderation team (this is already sort of in the works from sides of the inclusivity WG). as for the active contributor issue, we could try actively recruiting people from the very active node core to the other, newer and therefore less popular WGs/projects.

a large step has already been done by ratifying the inclusivity WG, but now we need to ensure that we keep on heading the right way, and this has to happen by actively making efforts to address the most important issues.

**Comment by junosuarez** [comment]
Thanks for the reply!

**Comment by rvagg** [comment]
thanks for nominating @sup, great to have you as part of this process.

**Comment by mikeal** [comment]
Election is over, results are [posted](https://github.com/nodejs/membership/blob/master/README.md#2016-election).
