### ISSUE TITLE
Q&A w/ @tejasmanohar on Individual Membership Candidacy

### ISSUE THREAD

**Issue by mikeal** [nodejs/board#25]
This thread is for asking @tejasmanohar questions regarding [his run](https://medium.com/@tejasmanohar/node-js-foundation-board-of-directors-5514e8faa660) 
for the Node.js Foundation Board of Directors.

**Comment by jasnell** [comment]
(A) If elected, what do you envision would be three most important issues that need to be addressed and how would you go about advocating for / resolving those?

(B) In a single sentence, how would you describe the role of the person elected to the board?

**Comment by rosskukulinski** [comment]
Hi @tejasmanohar.  Thanks for applying to be an Individual Member of the board.  Should you be elected, how do you plan to listen and engage with the large (and growing) NodeJS community and then channel that back to the Board?

**Comment by junosuarez** [comment]
1. What do you see as the most significant obstacle to node.js's continued growth?
2. What do you think the node.js foundation can do to address your answer to #1?

**Comment by rvagg** [comment]
ping @tejasmanohar

**Comment by tejasmanohar** [comment]
Hey all!

I'd say that the most significant obstacles to the platform's growth at the moment are
- average skill level amongst Node.js developers / solving the "gap"
- limiting release cycle

Thus, I believe the most important issues to address are as follows:
- Upgrading documentation so that it's readable to those with no prior programming experience and pointing them in the right direction to nail down fundamental JS before starting (in short, community <> resource building).
- Making sure the release cycle doesn't limit individuals. I whole-heartedly agree w/ @domenic's reasoning [here](https://github.com/nodejs/node/issues/1997).
- Keeping things BS-free by making sure everything is done with good intents while laying utmost emphasis on technical issues.

**Comment by mikeal** [comment]
Election is over, results are [posted](https://github.com/nodejs/membership/blob/master/README.md#2016-election).
