### ISSUE TITLE
Q&A w/ @watson on Individual Membership Candidacy

### ISSUE THREAD

**Issue by mikeal** [nodejs/board#27]
This thread is for asking @watson questions regarding [his run](https://medium.com/@wa7son/why-i-m-running-for-the-node-js-foundation-board-of-directors-253bc2e3a834#.oarxi35e2) 
for the Node.js Foundation Board of Directors.

**Comment by jasnell** [comment]
(A) If elected, what do you envision would be three most important issues that need to be addressed and how would you go about advocating for / resolving those?

(B) In a single sentence, how would you describe the role of the person elected to the board?

**Comment by rosskukulinski** [comment]
Hi @watson!  Thanks for applying to be an individual member of the board.  I read your application and I was wondering if you could expand more on how the needs of the non-US node community differs from that of the US userbase (which is already well represented by the board).

**Comment by junosuarez** [comment]
1. What do you see as the most significant obstacle to node.js's continued growth?
2. What do you think the node.js foundation can do to address your answer to #1?

**Comment by watson** [comment]
@mikeal great idea with an Q&A

### @jasnell

> (A) If elected, what do you envision would be three most important issues that need to be addressed and how would you go about advocating for / resolving those?

I think 3 very important issues are:
- It's easy to see the Foundation having a cooperate agenda because of its founding member companies. This might not actually be true, but it's something that I as a community representative will work hard to ensure isn't the case. A part of this also involves ensuring the openness of the foundation to make sure the community feel properly represented
- A lot of people are still unsure about the role of the Node.js Foundation. It's important to raise awareness of the foundation and the work it does
- It's not easy being a Node core dev. In general there's too much work for too few people and it's important to make it even easier to contribute to Node core
- Bonus issue: A lot of developers who work with Node every day are not engaged in or even know about the Node community. As a community representative I'd work to engage more developers from outside the community

> (B) In a single sentence, how would you describe the role of the person elected to the board?

The elected person should work hard to represent the interests of the Node.js community on the board.

### @rosskukulinski

> I read your application and I was wondering if you could expand more on how the needs of the non-US node community differs from that of the US userbase (which is already well represented by the board).

Thanks for reading my blog post and asking about the non-US node community. I think the board have so far done a good job, but I think being emerged in the European Node community will allow me to better communicate the work of the board and voice questions or issues that might arise outside the US. But as mentioned in my blog post i'lll obviously represent every Node dev around the :earth_africa: 

### @jden

> 1. What do you see as the most significant obstacle to node.js's continued growth?

A lot of students coming out of universities have been thought more "enterprisey" languages. They look for jobs where they can use those languages.

> 1. What do you think the node.js foundation can do to address your answer to #1?

I hope the Node.js Foundation have the opportunity to influence actual coders to teach more Node.js CS causes. A good example I think is @diasdavid who's currently teaching Node.js at [University of Lisbon](http://tecnico.ulisboa.pt). He encourages students to open source their programming assignments and use [NodeSchool workshops](http://nodeschool.io/#workshopper-list) as part of the course. This is a great example of an alternative way to teach programming that engages students.

**Comment by rvagg** [comment]
Great responses @watson, thanks for this and for nominating!

**Comment by mikeal** [comment]
Election is over, results are [posted](https://github.com/nodejs/membership/blob/master/README.md#2016-election).
