### ISSUE TITLE
Q&A w/ @pgte on Individual Membership Candidacy

### ISSUE THREAD

**Issue by mikeal** [nodejs/board#29]
This thread is for asking @pgte questions regarding [his run](https://gist.github.com/pgte/cfbf468202b35be78c66) 
for the Node.js Foundation Board of Directors.

**Comment by jasnell** [comment]
(A) If elected, what do you envision would be three most important issues that need to be addressed and how would you go about advocating for / resolving those?

(B) In a single sentence, how would you describe the role of the person elected to the board?

**Comment by rosskukulinski** [comment]
Hi @pgte, thanks for applying to the board.  In your application you end with this statement:

> I was really happy when I found out that the Node Foundation wanted to give a voice to the individual members. I would be honored and thrilled to provide that voice, making sure individuals are heard and well represented.

If you are elected, how do you plan to listen to the large (and growing) nodejs community?  In addition, how do you view the balance between corporate and individual members of the community?

**Comment by junosuarez** [comment]
1. What do you see as the most significant obstacle to node.js's continued growth?
2. What do you think the node.js foundation can do to address your answer to #1?

**Comment by pgte** [comment]
@jasnell 

> (A) If elected, what do you envision would be three most important issues that need to be addressed and how would you go about advocating for / resolving those?

First I'm going to listen and keep listening to the community through reading forums, chat rooms, github issues and personal emails, going to conferences, etc. This off-line discussion is what ultimately will form the most pressing issues I will focus on.

We all want the same thing: we want the Node platform adoption to keep growing. There are a lot of conditions that have to be met for this to happen (and I'll evolve on these further down).

Here are what I think to hot topics will be for me (they're 4, not 3 as you asked, sorry...), but again, subject to change as I get the feedback from the community:

## Stability / new features

For some of the people that have been working the longest, the most pressing issues can be API stability (for those working for bigger companies) — the LTS has somewhat addressed this — , while others will push for new Node features or even V8 versions. Generally, most people will worry about runtime stability and performance. We need to know how we can continue working on how to create a model that a) maintains the balance between these two forces and b) provides resources for these to be solved.

There are obvious pain points that need to be addressed in the Node API (like the Streams implementation and others), but again:
- I plan to find these out not only from personal experience, but mainly from observing / talking to the community
- Having to balance features and stability so that upgrading Node will not be a hard experience.

## The beginner experience

We should also take care of the beginner experience: how they get started, how not to easily shoot yourself in the foot — and Node, being so powerful and low level, has a lot of rope for you to hang yourself with. So the beginner experience is important, as is the capability of quickly getting an implementation out. Node is known for how quickly you can prototype something, but it's also known for how it's hard to prevent (through education and good practises) and also hard to analyze when things go wrong. We need to keep fixing this experience.

## NPM and Licensing

Some people will be worried about licensing and NPM, and rightfully so.
Node being a low level API, most of the value is now being added in user space. This has the downside of introducing fragmentation, but at the same time has lead to diversity and growth. We can now find a package for almost anything in NPM, and if we don't, we'll quickly create it and push it there.

But lately, [some concerns](https://github.com/nodejs/node/issues/3959) have [been raised](https://github.com/nodejs/TSC/issues/21) with the licensing agreement and the bundling of the NPM client. Although bundling NPM is great for the beginner experience, having an open-source foundation-led project make the default repo point to a registry provided by a private company is questionable.

I'm not a lawyer and so I'm not yet sure what would be the ideal solution, but I believe that we need to work ona roadmap that will lead to making Node less tightly coupled with the NPM client and the NPM Inc. service, (perhaps using a descentralized approach), led by a specific TSC working group.

## Education

Making education more accessible is how we make the community grow and is how we can help less privileged people become a part of this, becoming productive and so help raising their local communities.
Having been the creator of some of the first existing resources for learning Node.js, I care about this a lot. My education (and lately, Node), has been what has allowed me to break out from this (relatively) unprivileged part of the world (economically and culturally speaking), helping my family (and the local community somewhat).

I picture the Node community helping people crossing over the economic chasm, and this is a happy image. This is a bit lyrical, but it's true, I've seen this happen a lot of times in the last few years.

But of course, we still have a long way to go, and the Foundation must guide and support these efforts: Node schools, Node bots, meetups, screencasts, tutorials, documentation, beginner experience, and many many others to come.

> (B) In a single sentence, how would you describe the role of the person elected to the board?

If elected, I'll be someone that represents these and other aspects of the community concerns, that makes a real effort to listen and then act with the intent of making Node a fair and accessible platform, making sure it has a clear and transparent path that allows it to keep gaining adoption and be perceived as good — in every possible sense.

**Comment by pgte** [comment]
@rosskukulinski 

> > I was really happy when I found out that the Node Foundation wanted to give a voice to the individual members. I would be honored and thrilled to provide that voice, making sure individuals are heard and well represented.
> 
> If you are elected, how do you plan to listen to the large (and growing) nodejs community?

I plan to read forums, chat rooms, github issues and personal emails, going to conferences, etc, asking engaging with developers and the community in general. I also plan to create a more structured approach using polls, surveys, etc.

> In addition, how do you view the balance between corporate and individual members of the community?

Being a community-driven platform, I'll be opposed to all and any resolution that is somewhat designed to land-grab or benefit any set of corporations, member or non-member. We need to make Node.js a fair ground for everyone and opportunity must come from it's adoption, not from political decisions.

**Comment by pgte** [comment]
@jden 

> 1. What do you see as the most significant obstacle to node.js's continued growth?

Node has lately met unprecedented growth.
There are a lot of issues / initiatives that would be important to me, (and I'll be scanning the community for these,) but my personal opinion about what's holding back Node is the (bad) perception derived from the conflict between the NPM (company) and the NPM (open-source project). By bundling and coupling with NPM (both the company and the open-source project), I feel that we're not  being transparent about which initiatives are commercial in nature.

> 2. What do you think the node.js foundation can do to address your answer to #1?

The Foundation should inform the community of the various options and cannot be seen to be supporting any given solution.

We need an official response to this, and we need to create a plan that unbundles and decouples Node from NPM (Inc.). The Foundation should also create / sponsor / sanction an alternative for the NPM service. In the interim, developers need to have information out there on how to use existing alternatives.

**Comment by scriptjs** [comment]
@pgte I am quite happy that you are applying and have referenced the issues I have raised. These are serious concerns and more than ever, developers at large need a voice to ensure this translates into positive actions for the community. You will note there is more discussion on these topics has been occurring in the following issues:

https://github.com/nodejs/node/issues/3955
https://github.com/nodejs/NG/issues/26

Issues of community involvement concerning the package.json manifest has also hit a nerve and discussion continues while NPM feels it is resolved

https://github.com/nodejs/node/issues/3949
https://github.com/npm/npm/issues/10479
https://github.com/npm/npm/issues/8918

Transparency around security issues also needs to be a priority. Consider the following and whether this was broadly reported to users:

https://github.com/nodejs/node/issues/4660
https://www.youtube.com/watch?v=Qj4zbnI-4Jw

The issue with npm's terms has still to be reviewed by NF lawyers for the millions of downloads that occurred where NPM attached their Terms of Service to the NPM client and Artistic License in downloads without their knowledge. The fact that the license people accepted in the download and what they saw on the node.js site was different that what landed on their systems remains a serious concern and I am looking forward to understanding the legal implications and an appropriate remedy.

https://github.com/nodejs/node/issues/3959

**Comment by rvagg** [comment]
Thanks for nominating @pgte, it's great to have someone running who's been around this community as long as you have!

**Comment by mikeal** [comment]
Election is over, results are [posted](https://github.com/nodejs/membership/blob/master/README.md#2016-election).
