### ISSUE TITLE
Discussion: Membership Levels and Collaborators

### ISSUE THREAD

**Issue by jasnell** [nodejs/board#3]
1. What will the Foundation membership levels be? 
2. Currently, there is no requirement that a Collaborator also must be a member of Foundation. It seems reasonable to require that Collaborators also maintain their membership (either as individuals or through affiliation with a member organization)

**Comment by Morgul** [comment]
> It seems reasonable to require that Collaborators also maintain their membership (either as individuals or through affiliation with a member organization)

My gut reaction is to dislike this. "Oh, you want repo access? Pay up." I don't like limiting the pool of potential collaborators by those willing to give money to the foundation. I think it undervalues the contributions of collaborators. It's essentially saying that the collaborator's time has no intrinsic worth to the foundation.

Some of this is mitigated by the membership levels; if, say there's a cheaper 'collaborator' level (something that recognizes that the dues are being paid in time/effort and money) specifically for people who have been made collaborators, then I'm ok with still requiring dues for collaborators. (Also, how does one become a collaborator? I assume a vote of the TC?)

**Comment by jasnell** [comment]
Not necessarily: Individual non-members who are invited to become Collaborators could be granted a membership (in other words, their contributions become their entrance ticket).

**Comment by Morgul** [comment]
Interesting; would that be for life? (Probably not) For a year? If for a year, I'd still like a collaborator's discount, but maybe something like 20%?

The more I think about it, the more your suggestion there feels like a pretty good middle-ground.

**Comment by Morgul** [comment]
Thinking about membership levels, there's a couple of groups we want to make sure we cover:
- Students/Academics
  - Needs to be cheap, no more than $50/yr, possibly free w/ board approval
  - Incentives need to be oriented at academics
    - ex: Free node.js training on sites like codeschool?
    - ex: Free professional ide license? ([Jetbrains](https://www.jetbrains.com/student/) already offers free copies to students...)
- Professional Node developers
  - Around $99/yr
    - If we price this correctly, we could orient it such that companies that are unwilling to spend $5000 on being Silver members, might still be willing to spend the money paying for their three or four node devs.
  - Incentives should be targeted at the needs/likes of "in the wild" developers.
    - ex: discount on hardware (maybe bolster node on arm by offering discounted arm boards?)
    - ex: branded "swag" (t-shirts, mugs, water bottles)
    - ex: free cloud storage (Google/Dropbox?)
- Node.js Rockstars/Evangelists
  - Around $150+/yr
  - Incentives at this level should basically be a super set of the previous, with an emphasis on choices.

**Comment by mikeal** [comment]
The cost we'd discussed on the Advisory Board call was
- $25/year for Students
- $99/year for Everyone Else

This is the same setup the Linux Foundation uses.

We may want to reconsider sending a shirt for _every_ member signup because the international shipping can easily make the total cost of a single shirt $40-$50 through a fulfillment company. Maybe it would be a better idea to have a storefront for shirts and a 50% off policy for all foundation members (before shipping).

I don't like the idea of adding "tiers" to individual membership other than a discount for students. The main purpose of this membership is to elect a representative to the board as a class and I don't thing having additional tiers sends the right message about what membership means in this context.

And, just to make it very clear, **membership in the foundation is not tied to repository access or ability to contribute to any project**.

**Comment by jasnell** [comment]
@mikeal ... yes, membership is not tied to repository access or contribution, but should all collaborators be members? Or... how do we incentivize collaborators to become members? The main idea is: contributions to the project are valuable, there should be some additional benefit and incentive to becoming a collaborator.

**Comment by mikeal** [comment]
> but should all collaborators be members

We should offer it at a discount, but how are we defining "collaborator?" Is that _just_ core or is that the whole org (290 members last time I checked). And if it's the org do we extend it to every new org that comes in to the foundation as we bring in more projects?

**Comment by jasnell** [comment]
An initial discount for anyone with the commit bit and some minimal threshold of contributions would be reasonable, I think. Perhaps only for the initial membership tho. Renewals would be at the normal rate, etc.

**Comment by mikeal** [comment]
If we end up having people auth with GitHub before signing up then we can pretty easily check if they are a member of any of the orgs the foundation hosts.

**Comment by Morgul** [comment]
@mikeal, I seem to have been misunderstanding (some) of what was intended by individual membership.

As I understand it now (please correct, if I'm still off base), being an individual member, simply gives you the right to run for the "Community" board seat, and the ability to vote on it, plus what ever other incentives we decide on. Correct?

In that case, my proposal changes to:

**Student**
- $25/yr
- Can vote for Community Director board seat
- Other incentives TBD.

**Member**
- $99/yr
- Can vote for Community Director board seat
- Can run for Community Director board seat
- Other incentives TBD.

(I would also specify that to run for the board seat, you cannot already be on the TSC, already a board member, or a member of a Platinum organization. This cuts down on double representation.)

I definitely agree that repo access should not be related to membership status. Though I'm still in favor of the discount. I slightly disagree with @jasnell; a 10 - 20% discount because of the work you do as a collaborator seems reasonable, even on renewal. Heck, it (slightly) encourages people who want to be members to become collaborators, something I think is positive over all.

**Comment by mikeal** [comment]
Real quick, I'm all for the individual membership but I'm -1 on calling it the "community seat" for the same reason that I find roles like "community manager" so counterproductive. We are all part of the community and working with the community is literally part of everyone's role. But others might feel differently and I may be entirely outvoted on this issue and it'll be called the community seat ;)

**Comment by mikeal** [comment]
> (I would also specify that to run for the board seat, you cannot already be on the TSC, already a board member, or a member of a Platinum organization. This cuts down on double representation.)

Good point, although I think the "member of a platinum org" is probably not important. For one thing, if this person isn't well respected by the community they won't be elected. Also, unlike corporate member seats this seat would stay with this person regardless of what employer they might move to which is quite different than the corporate seats.

**Comment by Morgul** [comment]
> Real quick, I'm all for the individual membership but I'm -1 on calling it the "community seat"

Eh, it was for lack of a better term. I lean towards your preference; "Individual Membership Representative", or something is probably a better term.

>  I think the "member of a platinum org" is probably not important.

Mostly trying to cover the bases, as I could see them. Your later point about the seat moving with them regardless of organization could make that problematic, so yeah, that's fine.

**Comment by timofonic** [comment]
@Morgul

That's like Linus giving finger to Nvidia, but being part of Linux Foundation. The same with other organizations ;)
