### ISSUE TITLE
Linux Foundation quietly drops community representation

### ISSUE THREAD

**Issue by joshmanders** [nodejs/board#32]
http://mjg59.dreamwidth.org/39546.html

Since Node.js Foundation is part of the Linux Foundation, how does this affect Node.js and the current elections right now?

**Comment by jasnell** [comment]
This should have no impact on the Node.js Foundation. While NF falls under the larger Linux Foundation umbrella, the NF has it's own by-laws and processes that are independent of the LF itself.

**Comment by joshmanders** [comment]
Excellent. I saw that and was immediately worried because of the community director elections going on right now.

**Comment by watson** [comment]
It's still very worrying though - it's an indication that something is rotten in the top of LF - if the article is to be taken word by word of cause

**Comment by Danese** [comment]
We explicitly added membership representation via election to our By-Laws. The LF didn't include it in their boilerplate setup for us...and I really can't understand why. It's so basic to good open source governance.

D

**Comment by joshmanders** [comment]
I guess they don't want the community to have a say in anything in the Linux Foundation.

Glad to see Node.js Foundation thinks otherwise.

**Comment by mikeal** [comment]
To be clear, the Node.js Foundation is an independent entity. It's registered as its own non-profit in the state of Delaware, has its own bylaws, members and board of directors. The Node.js Foundation has a service agreement with the Linux Foundation, essentially hiring the LF to provide a number of services around administration, payroll, event management, marketing, public relations, etc.

This can be a little confusing because not every "Linux Foundation Collaborative Project" is setup the same way, some are more directly under the LF and some are setup like we are as independent entities.

Closing this out since this doesn't effect us, our Board, or our member elections :)

**Comment by joshmanders** [comment]
Thanks for the clarification @mikeal!
