### ISSUE TITLE
Q&A w/ @wprl on Individual Membership Candidacy

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/board#46]
This thread is for asking @wprl questions regarding [his run](https://medium.com/@wprl/i-would-like-to-represent-individual-members-of-the-node-js-foundation-977157d90aa0#.hq3vo8d8m) for the Node.js Foundation Board of Directors.

**Comment by nebrius** [comment]
Hi @wprl,

Thank you for running for the Node Foundation community seat! To help me and others get to know you better, I have a set of questions that I'm asking all candidates, listed below. I look forward to your answers!

1) How did you get involved in the Node Project?

1) What does inclusivity and diversity within the Node project look like to you? How would you work with the board to increase inclusivity and diversity within the Node project?

1) How would you work with the board to increase international participation in the Node project?

1) What do you think are the pros/cons about the separation of powers/responsibility between the TSC/CC and the Board? How would you improve it?

1) What do you think is the greatest weakness in the Node Project? How would you work with the board to fix it?

1) What do you think is the greatest strength in the Node Project? How would you work with the board to preserve it?

**Comment by ghost** [comment]
Hi @nebrius, thanks for your question.  And thank you @hackygolucky for setting up the thread.  

* 1

About 6 years ago, I was introduced to Node.js on a project at my job at the time.  There was really no looking back.  Very soon afterward, I began working for myself providing consulting and software development services remotely from my home office in semi-rural Missouri, USA to customers in (so far) Africa, Australia, Europe, North America, and South America.  What attracted me to using Node.js in my work is that it is open source and has a package manager full of good open source modules, there are fewer "moving parts" because the server and client can be written in the same language (as well as your data if using e.g. Mongo or Elastic), and of course the ease with which you can write asynchronous code in Node.

* 2 and 3

Node.js must serve the needs of individual developers and that includes people that are often undervalued in tech largely because of white, male, abled, and urban privilege.  I would take an iterative approach, focused on listening.  For the first "sprint" I would seek input from Node.js Foundation individual members and the community of individual developers as a whole.  I would pay particular attention to listening to underrepresented groups and making sure their voices are heard by the Board.  The results of the first sprint would inform the following sprints, which would be dedicated to enacting and continued listening.

* 4

This is something else I would seek input for.  On the surface, I would say that separating technical and administrative governance is good separation of concerns and encapsulation.  

* 5

A primary concern for me is addressing JavaScript fatigue without compromising my core beliefs that modules should "do one thing well" and that open source modules should be published early and often.  Avoiding the lock-in inherent in monolithic frameworks has been a driving force for my personal journey as a software developer working for myself.  However, this is just my opinion, and I would again focus on listening to the needs of the individual developers who use Node.

* 6

Open source, open source, open source.  Open source empowers individuals and making sure that Node.js continues and increases access to that power would be a primary concern for me.

**Comment by jasnell** [comment]
Just two quick questions from me: (a) In your view, what is the primary role of the Board in the evolution of the Node.js platform and (b) as an individual board member, what would be one thing you'd hope to accomplish over the next year?

**Comment by ghost** [comment]
Thanks for your questions, @jasnell.

a. I understand the purpose of the Board of Directors as overseeing non-technical aspects of Node.js, so that the TSC can focus on technical issues without getting bogged down in administrative details.  Basically, the Board should focus on the non-technical aspects of increasing adoption and improving the Node.js ecosystem.  

b. The role of Individual Membership Director I see not so much as an opportunity to accomplish my own goals, but as an opportunity to make sure the increasing adoption of Node.js by the enterprise (which is great and essential) is balanced by input from individual members of the Foundation and the community of individual Node.js developers at large (which is essential to ensuring that innovation continues and increases).

**Comment by Fishrock123** [comment]
Two questions (for each of the candidates):

@wprl:

1. How will you communicate with broader Node community you could be representing? What would be the primary avenue for questions and comments to yourself and to the board through yourself?
2. How would make future Individual Directors more effective, even continuing past the current term?

**Comment by ghost** [comment]
Thanks @Fishrock123.

1. There are a few obvious means I would pursue such as social media, email, surveys, and Slack or IRC.  Reaching across the [digital divide](https://en.wikipedia.org/wiki/Digital_divide) is also important.  Mobile Wi-Fi hotspots are one way to approach it.  Depending on the resources available to me, I would work iteratively to discover the best channels to gain understanding of present and future individual members and developers.

2. Documentation and automation.  I would work iteratively and document each "sprint" so that future Directors can learn from my successes (and failures).  Any processes that I could automate and open source can then be used by the community and by future Directors.
