### ISSUE TITLE
questions to the board, following yesterday's board statement 

### ISSUE THREAD

**Issue by ashleygwilliams** [nodejs/board#69]
i've been thinking a lot about our situation over the last few days and have been interacting with many members of the community, both those who are upset about the TSC vote and others that have concerns that it is being called into question. based on this feedback i have several questions which i intend to bring to the board for discussion that i will also advise would be good for us to comment on publicly.

**as a representative of the community, i would like to solicit feedback from ya'll on these questions. the questions as currently drafted are:**

### Proposed Questions to the Board

1. do we support the merge of the CTC and TSC? why do we support/not support it? how do we think it is related to the previous vote and how do we think it will affect the next vote?
2. if the vote of the merged CTC/TSC results in the same outcome as the previous vote, what do we think? do we intend to do anything? if so, what and why?
3. were there mistakes in the process? what were those mistakes? how do we intend to fix them moving forward? what do we think is the TSC's responsibility regarding this? what do we think our responsibility regarding this? what actions or recommendations do we have? (this is the classic "blameless portmortem"- focus on processes, not people, which is the angle i've been trying to drive in conversations with the community and think is a good strategy for us as a Board as well)

MODERATION: **comments that directly suggest new questions or edits to current or suggested questions are considered on topic.** comments that do not do this, and/or are argumentative or attempt to address the details of the current situation that are not then constructed into a question for the board will be considered off topic and moderated. if you are concerned whether your comment is on topic, feel free to message me privately at ashley@npmjs.com or @ag_dubs on twitter (DMs open).

EDIT: after i give this issue some time i will create a new issue soliciting feedback on the community as to what they would like the answers to these questions to look like, or be.

EDIT: to make this more clear i have created a heading above the questions and emphasis on the desired feedback. a few community members have been confused about whether this issue is soliciting answers to the questions, which it is not.

**Comment by zkat** [comment]
1. I believe the TSC should be disbanded altogether. It's not much of a difference because of the overlap, but I think it says something -- considering that one reason quoted to me for the CTC existing was to clean up legacy stuff. While it doesn't matter _that_ much, I think it sends a good message to be willing to disband the body.

2. I consider the result of the vote to be an unpleasant symptom of the larger systemic problem with Node.js governance. This point is moot, specially since the person in question has been essentially vestigial to this project for some time now -- only popping up rarely in conversations, and usually only in the context of "what the hell happened _now_?" So I don't think this is really about a specific case of a bad actor and whether to get rid of the one bad actor.

3. Whether "leaders" who make it their business to harass and attack their peers are meeting the high standards that the Node community deserves of those who represent them feels like an easy enough question to answer, for me -- that bureaucracy/bylaws/politics are able to so effectively get in the way of action speaks volumes about how ineffective the current system is. I believe it is the current leadership's responsibility, both at the Foundation and at the Core levels, to ensure that their processes promote the healthy growth and development of its community: not just benefitting its corporate overlords, or the wider community of users that never participate in actual core development, but also the collaborators and contributors who have to work within this system every day. I think the current structure was one which benefitted the original IO.js fork, for the problems they had then, but I do not believe the system set itself up to evolve further as its contexts changed. I would like to see a serious, deep re-evaluation of governance structures across both the board and the CTC, with the TSC no longer existing (since it was formulated before Linux Foundation happened, and already partially obsoleted by that). I would like to see more federation of project responsibilities such that the CTC is not a toplevel body anymore, but specifically responsible for one aspect of the project (the source code itself). I believe other WGs should be easy to spin off, easy to charter, and should be able to have significant freedom over _their own_ governance. Let's get rid of the piles of red tape that both the Documentation WG and the Inclusivity WG had to wade their way through before ultimately failing. You shouldn't have to be deep in the weeds of project politics to take on responsibility for an aspect of it.

**Comment by zkat** [comment]
<details> [_edit: I'm sorry, I asked Ashley about this and misunderstood the answer, please ignore this message because I thought she was seeking community answers, not community questions_] </details>

**Comment by refack** [comment]
<details>
<summary>addressed</summary>

@zkat please remove your unsolicited opinions as per @ashleygwilliams's request:
![image](https://user-images.githubusercontent.com/96947/29728376-a0331d24-89a5-11e7-9361-a1d74d1b93be.png)
</details>

**Comment by ashleygwilliams** [comment]
<details>
@refack @zkat has already done so. but thank you for your attention to my guidelines :) would you mind putting your response in a details section as to keep the convo focused on feedback and not moderation? (this is a common ask- thanks in advance!)
</details>

**Comment by hackygolucky** [comment]
To note:

It's helpful to understand that the Node.js Board of Directors is one of many groups within the Foundation, and in a sense creates a balance of powers with the Foundation through the TSC, Community Committee(both top-level in the project), the Board, and the executive(employees such as the Executive Director and Community Manager). What that means is that the scope of the Board of Directors in matter of the project work itself(such as the TSC, for instance), is generally one of being asked **to advise**. Regardless of whether people would argue the legal case in the charter for the Board having the ability to intervene, were it necessary, most foundations _want_ and prefer the committees and community to address and resolve conflict. 

If you keep this constraint in mind, providing questions for @ashleygwilliams and @williamkapke will be very constructive.

**Comment by niallobrien** [comment]
Are the board going to address the concerns raised that caused yet another fork of the project?
Also, what's the plan regarding the fork? Has there been open dialogue with the fork maintainers with the goal of merging back?

**Comment by geldan** [comment]
The alleged transgressions were made in the context of the current process and rules.  That process has already ruled that his actions do not warrant his removal from the project.  If people do not agree with the result and want to change the process then that should happen.  But, upon accomplishing change, is it reasonable or ethical to punish someone based on actions that occurred under a different set of rules?

**Comment by mikesherov** [comment]
A lot of what has happened is very much "inside baseball". To a layman member of the community, like myself, I'm having trouble understanding what the difference in purpose of the CTC and TSC are, and how a proposed merger of the two would rectify the situation that led to the failed vote.

Could the board please clarify the intent here? And what can the board do going forward to ensure the community is well equipped to understand these types of issues going forward?

**Comment by mcqj** [comment]
We seem to lack a robust conflict management process and this has caught all off guard.

Without knowing the facts, it seems that the Board in its statement has taken a partisan view to the issue that has been raised. Where it should have taken a completely non-partisan view prior to its discussions and investigations, it has compromised itself with respect to any intervention.

1. Will the Board consider external neutral arbitration to resolve conflicts where it has become compromised?
2. Will the Board respect future democratic decisions or reserve the right to overturn those that it does not support or agree with.

**Comment by djangoconcardiff** [comment]
1. What does the board consider to be the harm in allowing a person subject to a process that might result in her ejection from a committee to defend herself in the course of that process?

2. Does the board consider It consistent with human dignity to exclude a person from such a process?

3. If the board considers such secret adjudications to be so consistent, does the board have a plan for replacing the loss of talent (read: brain drain) that will occur as a result?

**Comment by bruncun** [comment]
Will the foundation make clear how its response adheres to the organization's mission?

**Comment by jcrben** [comment]
The questions on my mind, and I apologize if these are somehow misplaced:

* How much was Rod a part of the process and vote on his removal and what are the policies in place for his notice and right to respond or not? From https://github.com/nodejs/CTC/issues/165#issuecomment-324798494 it appears the answer is that he was privy to very little.
* It is my understanding that the CTC does teleconferences regularly, but it's not clear if some of these moderation discussions or any early intervention / de-escalation happened with voice (see question 1). Has there been consideration for intervening early with voice explaining concerns about behavior?
* How are presumptions of motivations and attacks on character handled under the Code of Conduct? (Echoing https://github.com/nodejs/node/issues/15011#issuecomment-324856216 somehow I feel paranoid that by even raising that question I risk becoming a target as a presumed sympathizer of malcontents.)

**Comment by hypesystem** [comment]
This is a bit broader than just related to the board's statement, but I think it touches on issues this whole case has brought to light:

Seeing as there is a lot of confusion about the very structure of the Node project, even from individuals somewhat involved and not just users, what will the board do (if anything) to encourage more general transparency of the organization and its procedures?

This extends to working groups: what will the board do to make it more visible how to contribute to the Node organization, especially in ways that do not directly involve code contributions?

Finally, what will the board do to encourage more (and more varied kinds of) contributions from a broader group of people, going forward?

**Comment by ashleygwilliams** [comment]
thank you all for your comments thus far! i am commenting to let you know that i will be closing this thread at 4pm EST in preparation for the board meeting at 5pm. if you would like to comment please do so before then.

**Comment by tkambler** [comment]
I would like to _respectfully_ bring to the attention of those on the board the following information. This is _not_ an attempt at trolling. I have _genuine_ concerns about what's happening here, and would like an opportunity to raise those concerns in a respectful manner. I simply want to share what I believe to be timely and important information and then sit back and allow the board to do its job. I thank you all in advance for giving me that opportunity.

Earlier this morning, a CoC complaint was filed against another member of the board who will be weighing in on issues regarding Rod Vagg. My concern is that a very real conflict of interest exists here. The full complaint can be found here:

[Multiple CoC violations by Node.js board member Ashley Williams](https://www.reddit.com/r/node/comments/6whs2e/multiple_coc_violations_by_nodejs_board_member/)

I have two questions that I respectfully ask be put to the board:

1. Do you believe these allegations warrant further discussion?
2. If so, do you believe there is a possibility of conflict of interest in regards to the issue(s) regarding Rod Vagg?

Excerpt:

> "I wish to formally file a series of Code of Conduct (CoC) violations by Ashley Williams (ag_dubs on twitter) who currently holds a position on the Node.js foundation's Board of Directors underneath the Linux Foundation umbrella. Given the evidence I'll present below, it is clear this individual has violated the CoC on multiple occasions in public forum and appears to harbor racist and sexist views and beliefs making her unfit for participation in the Node.js Foundation's projects, let alone leadership positions. This behavior has been observed since the conception of the Node.js foundation and it is unfortunate it has been allowed to persist for so long."

**Comment by jakeNiemiec** [comment]
_[Disclaimer: I admire the technical work that @.zkat has done. This is not targeted at them, **this targets the public pattern of offensive, CoC-violating behavior by those who champion CoCs the most.** I can't stress enough, it is not offence that I personally feel...it's disappointment in node.js leaders that I once looked up to.]_

Question:

- In a time of unrest after the events of last week. **How will the board handle the pattern of statements made by '`members`' such as the following?**

![image](https://user-images.githubusercontent.com/16782063/29785306-b174389a-8bec-11e7-983f-dccfab73eff0.png)

- Do you think that the general sentiment `"males are inferior, fragile, and incompetent babies"`by member, even in jest, could have influenced the vitriol and campaign of misinformation against `Rod Vagg`?

- Is twitter a valid source of CoC infractions? (as it was for `Rod Vagg`) Will this be changing?

- Apparent double-standards such as this (and the comment above) **shake the community's confidence in CoCs**, what steps will the board take to restore this confidence and ensure equal enforcement regardless of race or gender? 

[_Footnote: @.zkat [did make a statement](https://twitter.com/maybekatz/status/901654395707727872) on the reasons behind their tweet._]

**Edit:** The reaction to the well meaning comments and links by myself and @tkambler.
![image](https://user-images.githubusercontent.com/16782063/29792486-2caea324-8c06-11e7-8409-d06a84d1d53a.png)
This is not what npm/node.js leadership should look like.

**Comment by rachelnicole** [comment]
3. were there mistakes in the process? what were those mistakes? how do we intend to fix them moving forward? what do we think is the TSC's responsibility regarding this? what do we think our responsibility regarding this? what actions or recommendations do we have? (this is the classic "blameless portmortem"- focus on processes, not people, which is the angle i've been trying to drive in conversations with the community and think is a good strategy for us as a Board as well)

I think it's worth figuring out how to handle the backlash from communities that aren't involved in the day-to-day work we're all doing across the TSC / CTC / CommComm who only seem to care about it when rallied by anonymous accounts on various websites. It's incredibly derailing. 

Since a lot of the moderation work is done privately, the above causes a huge problem for those who are actually trying to make changes, when those not involved with the process come in and demand accountability. 

How are we going to provide accountability while also handling the moderation of issues, because the current process seems to make it so that parties can exploit it.

**Comment by ashleygwilliams** [comment]
closing as i need to prepare this feedback for the board meeting. thank you for your input!

**Comment by jakeNiemiec** [comment]
<details><summary>Details</summary>
@ashleygwilliams I know the time has passed, but could you please include the reaction to the well meaning comments and links by myself and @tkambler.
![image](https://user-images.githubusercontent.com/16782063/29792486-2caea324-8c06-11e7-8409-d06a84d1d53a.png)
This is not what npm/node.js leadership should look like.
</details>

**Comment by tkambler** [comment]
** contents removed **
(comments created by replying to an email do not allow html <details> tags)

**Comment by tkambler** [comment]
If the board's leadership has a shred of dignity or a professional bone in their body, they will address this. @ashleygwilliams @zkat @jakeNiemiec @refack

**Comment by ashleygwilliams** [comment]
<details>
<summary>Contents from above comment moved here since HTML wasn't allowed -Wm</summary>
The precise definition of "misandry" is:

> "dislike of, contempt for, or ingrained prejudice against men (i.e., the male sex)."

I concur with Mr. Niemiec. If there is a professional bone in the board's body - if they have a shred of decency - they will address this. @ashleygwilliams @zkat @jakeNiemiec @refack 
</details>
<br>
<details>
hello @tkambler and @jakeNiemiec i had asked politely that the issue be closed as i have only so much time to prepare for the meeting. i ask, in an effort at fairness that you moderate your comments by placing them in a `details` field:

- they are on a closed issue that gave warning of closing
- @tkambler follow up is not considered on topic given the MODERATION statement in the original issue filing.
</details>

**Comment by Marak** [comment]
<details>
I've been involved with the Node.js community since 2009. I was one of it's first users and helped raise millions of dollars to fund Node.js development. Many of my former employees are still active core contributors.

Sometime last month I had to block both @ashleygwilliams and @zkat over social media due to harassment. These people are bullies and should not be allowed to negatively influence the project in which I've spent years of my life helping foster.
</details>

**Comment by ashleygwilliams** [comment]
<details>
@Marak that statement is made on a closed issue, and is not fitting with the Moderation guidelines listed in the original issue. please moderate your comment by placing all offtopic statements in a `details` block.
</details>
