### ISSUE TITLE
Election rules and eligibility

### ISSUE THREAD

**Issue by guyellis** [nodejs/board#8]
In order to elect a member from the community we need to establish rules for the election and eligibility for running for board representative.

Eligibility already discussed:
- A member of the TC is not eligible.
- An employee of a company that already has a representative on the board is eligible.

Rules for election:
- @Danese is there an existing model we can base this off?

**Comment by Morgul** [comment]
Just to throw my $0.02 into the ring, I'm a fan of [Single Transferable Vote](http://en.wikipedia.org/wiki/Single_transferable_vote). In short, you mark down your top choice from the ballot, your second choice, and your third choice. It's pretty simple to calculate who one from that; the wikipedia article goes into some of the rules around it.

**Comment by Danese** [comment]
There are several. See: 

-Drupal's annual Community Seat election https://assoc.drupal.org/blog/holly.ross.drupal/get-ready-2015-community-elections

-Apache's use of STV
https://wiki.apache.org/general/BoardVoting

-Wikipedia's way to elect to Wikimedia Board
http://meta.m.wikimedia.org/wiki/Wikimedia_Foundation_elections_2015/MassMessages/Board_voting_has_begun

-Debian Linux's voting method
https://www.debian.org/vote/

There are others...

D

**Comment by Danese** [comment]
Apache has code available (and permissively licensed) for STV. It's how the elect their whole board.

D

**Comment by mikeal** [comment]
We'll already have every member's GitHub handle so creating a simple signin for that allows them to vote shouldn't be too difficult. I'd like to avoid a formal nomination period where we have to maintain a list of people running and instead let anyone announce that they would like to be considered and then have the people voting enter the GitHub username of the person they want to vote for.

**Comment by Danese** [comment]
Some of the references I sent earlier will have eligability rules. Over time these can become somewhat tortured, IMHO.

For instance, here is what Wikimedia Foundation tells its candidates (from http://meta.wikimedia.org/wiki/Wikimedia_Foundation_elections/Board_elections/2015 http://meta.wikimedia.org/wiki/Wikimedia_Foundation_elections/Board_elections/2015 ):

Prerequisites to candidacy
To be eligible, candidates must be willing and able to fulfill the duties of board and committee service, including expending the time and energy required to conduct due inquiry into relevant issues, to make informed decisions in good faith, and to attend board meetings regularly. The eligibility requirements for candidates are the same as for voters (see voter requirements http://meta.wikimedia.org/wiki/Special:MyLanguage/Wikimedia_Foundation_elections_2015#Requirements), with the following additional requirements:
You must not have been convicted of a serious crime or any crime involving dishonesty or deception; and
You must not have been removed from a position at a non-profit organization or other company because of mismanagement or misconduct; and
At the time of nomination or election, you may not be banned or blocked from any Wikimedia project for a period of 30 days or longer; and
You must publicly disclose your real name in your candidate presentation (because the identities of Board members are a matter of public record, it is not possible to hold a position on the Board of Trustees anonymously or under a pseudonym); and
Be at least 18 years old and of legal age in your home country; and
Submit proof of your identity to the Wikimedia Foundation (see below).

D

**Comment by guyellis** [comment]
I like the way Apache has implemented STV. That's currently my favorite.
